Fix incorrect syntax in if statement
When I tried to install this today I got the following error:

Error: Could not autoload puppet/parser/functions/agent_key: /etc/puppet/modules/serverdensity/lib/puppet/parser/functions/agent_key.rb:113: syntax error, unexpected ':', expecting keyword_then or ';' or '\n'
/etc/puppet/modules/serverdensity/lib/puppet/parser/functions/agent_key.rb:124: syntax error, unexpected keyword_elsif, expecting keyword_end
        elsif api_version == "2"
             ^
/etc/puppet/modules/serverdensity/lib/puppet/parser/functions/agent_key.rb:181: syntax error, unexpected keyword_end, expecting $end
Error: Could not autoload puppet/parser/functions/agent_key: /etc/puppet/modules/serverdensity/lib/puppet/parser/functions/agent_key.rb:113: syntax error, unexpected ':', expecting keyword_then or ';' or '\n'
/etc/puppet/modules/serverdensity/lib/puppet/parser/functions/agent_key.rb:124: syntax error, unexpected keyword_elsif, expecting keyword_end
        elsif api_version == "2"
             ^
/etc/puppet/modules/serverdensity/lib/puppet/parser/functions/agent_key.rb:181: syntax error, unexpected keyword_end, expecting $end on node bs7.dh.bytemark.co.uk
Error: Could not autoload puppet/parser/functions/agent_key: /etc/puppet/modules/serverdensity/lib/puppet/parser/functions/agent_key.rb:113: syntax error, unexpected ':', expecting keyword_then or ';' or '\n'
/etc/puppet/modules/serverdensity/lib/puppet/parser/functions/agent_key.rb:124: syntax error, unexpected keyword_elsif, expecting keyword_end
        elsif api_version == "2"
             ^
/etc/puppet/modules/serverdensity/lib/puppet/parser/functions/agent_key.rb:181: syntax error, unexpected keyword_end, expecting $end on node

This was caused by a `:` at the end of an if that should not have been there: